version: '3.8'

services:
  istar-monitor:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - nodered
      - paso
    
  nodered:
    image: nodered/node-red:4.0.5-22
    ports:
      - "1880:1880"
    volumes:
      - ./experiment:/data
      
  paso:
    image: smartifact/engine:v2
    ports:
      - "8083:8083"
